# Generated by Django 5.0.6 on 2024-05-29 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_alter_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Trending', 'Trending'), ('Classic', 'Classic'), ('Love', 'Books We Love')], default='yesss', max_length=50),
            preserve_default=False,
        ),
    ]
